import test from 'node:test';
import assert from 'node:assert/strict';
import {reconcile,changeMember,deadlinePassed,registrationClosed,kickoff} from '../netlify/functions/registration-rules.js';
const now=Date.UTC(2026,8,23,22,0); // 6pm EDT; kickoff 10pm EDT
const game=()=>({date:'2026-09-23',start:'22:00',capacity:20,priorityHours:2,registrationOpen:true});
function state(memberCount=16,guestCount=4){return {game:game(),safrookMembers:Array.from({length:memberCount},(_,i)=>({name:'Member '+i,active:true})),memberAvailability:{},guestRecords:Array.from({length:guestCount},(_,i)=>({name:'Guest '+i,status:'confirmed',paid:i===3,registeredAt:now+i*1000,confirmedAt:now+i*1000}))}};
test('kickoff uses Eastern daylight saving time',()=>assert.equal(kickoff(game()),Date.UTC(2026,8,24,2)));
test('priority deadline configurable to 2 or 3 hours',()=>{const s=state();assert.equal(deadlinePassed(s.game,now+2*3600000),true);s.game.priorityHours=3;assert.equal(deadlinePassed(s.game,now+3600000),true)});
test('20-player full game: returning member displaces last confirmed unprotected guest',()=>{const s=state(16,4);s.memberAvailability['Member 0']=false; // 15+4=19, add another confirmed guest
s.guestRecords.push({name:'Guest 4',status:'confirmed',registeredAt:now+5000,confirmedAt:now+5000});changeMember(s,'Member 0',true,now);assert.equal(s.memberAvailability['Member 0'],true);assert.equal(s.guestRecords.at(-1).status,'waiting');assert.equal(s.guestRecords.filter(g=>g.status==='confirmed').length,4);assert.equal(s.guestRecords.at(-1).paid,undefined)});
test('protected guest is skipped when choosing displacement',()=>{const s=state(16,4);s.memberAvailability['Member 0']=false;s.guestRecords.push({name:'Guest 4',status:'confirmed',protectedSpot:true,registeredAt:now+5000,confirmedAt:now+5000});changeMember(s,'Member 0',true,now);assert.equal(s.guestRecords[3].status,'waiting');assert.equal(s.guestRecords[4].status,'confirmed')});
test('paid displaced guest retains payment and original registration priority',()=>{const s=state(16,4);s.memberAvailability['Member 0']=false;s.guestRecords.push({name:'Guest 4',status:'confirmed',registeredAt:now+5000,confirmedAt:now+5000});s.guestRecords[4].paid=true;changeMember(s,'Member 0',true,now);assert.equal(s.guestRecords[4].paid,true);assert.equal(s.guestRecords[4].queueSince,now+5000)});
test('after deadline member cannot displace confirmed guest',()=>{const s=state(16,4);s.memberAvailability['Member 0']=false;s.guestRecords.push({name:'Guest 4',status:'confirmed',registeredAt:now+5000,confirmedAt:now+5000});changeMember(s,'Member 0',true,now+3*3600000);assert.equal(s.memberAvailability['Member 0'],'waiting');assert.equal(s.guestRecords.filter(g=>g.status==='confirmed').length,5)});
test('capacity increase promotes every eligible guest',()=>{const s=state(15,1);s.guestRecords.push(...[0,1].map(i=>({name:'Waiting '+i,status:'waiting',registeredAt:now+i})));s.game.capacity=20;reconcile(s,now);assert.equal(s.guestRecords.filter(g=>g.status==='confirmed').length,3);assert.equal(s.guestRecords.filter(g=>g.status==='waiting').length,0)});
test('cancellation promotes first waiting guest',()=>{const s=state(16,4);s.guestRecords.push(...[0,1].map(i=>({name:'Waiting '+i,status:'waiting',registeredAt:now+i})));changeMember(s,'Member 0',false,now);assert.equal(s.guestRecords[4].status,'confirmed');assert.equal(s.guestRecords[5].status,'waiting')});
test('after deadline queue is chronological across member and guest',()=>{const s=state(16,4);s.memberAvailability['Member 0']='waiting';s.memberWaitSince={'Member 0':now+2000};s.guestRecords.push({name:'Earlier Guest',status:'waiting',registeredAt:now+1000});s.game.capacity=20;reconcile(s,now+3*3600000);assert.equal(s.guestRecords.at(-1).status,'confirmed');assert.equal(s.memberAvailability['Member 0'],'waiting')});
test('kickoff closes self registration',()=>{const s=state();assert.equal(registrationClosed(s.game,kickoff(s.game)),true);assert.equal(registrationClosed(s.game,now),false)});
